package ProjectionalQiChat.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_NAOqiEvents extends EnumerationDescriptorBase {

  public EnumerationDescriptor_NAOqiEvents() {
    super(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x6fd223061c49b175L, "NAOqiEvents", "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606197");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_ALBasicAwareness1HumanTracked_0 = new EnumerationDescriptor.MemberDescriptor("ALBasicAwareness1HumanTracked", "HumanTracked", 0x6fd223061c49b176L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606198");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALBasicAwareness1HumanLost_0 = new EnumerationDescriptor.MemberDescriptor("ALBasicAwareness1HumanLost", "HumanLost", 0x6fd223061c49b177L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606199");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALBattery1BatteryLow_0 = new EnumerationDescriptor.MemberDescriptor("ALBattery1BatteryLow", "BatteryLow", 0x6fd223061c49b17aL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606202");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALChestButton1SimpleClickOccurred_0 = new EnumerationDescriptor.MemberDescriptor("ALChestButton1SimpleClickOccurred", "ChestButtonClicked", 0x6fd223061c49b17eL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606206");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALChestButton1DoubleClickOccurred_0 = new EnumerationDescriptor.MemberDescriptor("ALChestButton1DoubleClickOccurred", "ChestButtonClickedTwice", 0x6fd223061c49b183L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606211");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALChestButton1TripleClickOccurred_0 = new EnumerationDescriptor.MemberDescriptor("ALChestButton1TripleClickOccurred", "ChestButttonClickedThrice", 0x6fd223061c49b189L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606217");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALMotion1MoveFailed_0 = new EnumerationDescriptor.MemberDescriptor("ALMotion1MoveFailed", "MoveCommandFailed", 0x6fd223061c49b190L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606224");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALMotion1Stiffness1restStarted_0 = new EnumerationDescriptor.MemberDescriptor("ALMotion1Stiffness1restStarted", "RestStarted", 0x6fd223061c49b198L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606232");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALMotion1Stiffness1restFinished_0 = new EnumerationDescriptor.MemberDescriptor("ALMotion1Stiffness1restFinished", "RestFinished", 0x6fd223061c49b1a1L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606241");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALMotion1Stiffness1wakeUpStarted_0 = new EnumerationDescriptor.MemberDescriptor("ALMotion1Stiffness1wakeUpStarted", "WakeUpStarted", 0x6fd223061c49b1abL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606251");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALMotion1Stiffness1wakeUpFinished_0 = new EnumerationDescriptor.MemberDescriptor("ALMotion1Stiffness1wakeUpFinished", "WakeUpFinished", 0x6fd223061c49b1b6L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606262");
  private final EnumerationDescriptor.MemberDescriptor myMember_RightBumperPressed_0 = new EnumerationDescriptor.MemberDescriptor("RightBumperPressed", "RightBumperPressed", 0x6fd223061c49b1c2L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606274");
  private final EnumerationDescriptor.MemberDescriptor myMember_LeftBumperPressed_0 = new EnumerationDescriptor.MemberDescriptor("LeftBumperPressed", "LeftBumperPressed", 0x6fd223061c49b1cfL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606287");
  private final EnumerationDescriptor.MemberDescriptor myMember_BackBumperPressed_0 = new EnumerationDescriptor.MemberDescriptor("BackBumperPressed", "BackBumperPressed", 0x6fd223061c49b1ddL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606301");
  private final EnumerationDescriptor.MemberDescriptor myMember_FronTactilTouched_0 = new EnumerationDescriptor.MemberDescriptor("FronTactilTouched", "ForntTactilTouched", 0x6fd223061c49b1ecL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606316");
  private final EnumerationDescriptor.MemberDescriptor myMember_MiddleTactilTouched_0 = new EnumerationDescriptor.MemberDescriptor("MiddleTactilTouched", "MiddleTactilTouched", 0x6fd223061c49b1fcL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606332");
  private final EnumerationDescriptor.MemberDescriptor myMember_RearTactilTouched_0 = new EnumerationDescriptor.MemberDescriptor("RearTactilTouched", "RearTactilTouched", 0x6fd223061c49b20dL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606349");
  private final EnumerationDescriptor.MemberDescriptor myMember_HandRightBackTouched_0 = new EnumerationDescriptor.MemberDescriptor("HandRightBackTouched", "HandRightBackTouched", 0x6fd223061c49b21fL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606367");
  private final EnumerationDescriptor.MemberDescriptor myMember_HandLeftBackTouched_0 = new EnumerationDescriptor.MemberDescriptor("HandLeftBackTouched", "HandLeftBackTouched", 0x6fd223061c49b232L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606386");
  private final EnumerationDescriptor.MemberDescriptor myMember_FaceDetected_0 = new EnumerationDescriptor.MemberDescriptor("FaceDetected", "FaceDetected", 0x6fd223061c49b246L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606406");
  private final EnumerationDescriptor.MemberDescriptor myMember_WavingDetection1PersonWaving_0 = new EnumerationDescriptor.MemberDescriptor("WavingDetection1PersonWaving", "PersonWaving", 0x6fd223061c49b25bL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606427");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x6fd223061c49b175L, 0x6fd223061c49b176L, 0x6fd223061c49b177L, 0x6fd223061c49b17aL, 0x6fd223061c49b17eL, 0x6fd223061c49b183L, 0x6fd223061c49b189L, 0x6fd223061c49b190L, 0x6fd223061c49b198L, 0x6fd223061c49b1a1L, 0x6fd223061c49b1abL, 0x6fd223061c49b1b6L, 0x6fd223061c49b1c2L, 0x6fd223061c49b1cfL, 0x6fd223061c49b1ddL, 0x6fd223061c49b1ecL, 0x6fd223061c49b1fcL, 0x6fd223061c49b20dL, 0x6fd223061c49b21fL, 0x6fd223061c49b232L, 0x6fd223061c49b246L, 0x6fd223061c49b25bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_ALBasicAwareness1HumanTracked_0, myMember_ALBasicAwareness1HumanLost_0, myMember_ALBattery1BatteryLow_0, myMember_ALChestButton1SimpleClickOccurred_0, myMember_ALChestButton1DoubleClickOccurred_0, myMember_ALChestButton1TripleClickOccurred_0, myMember_ALMotion1MoveFailed_0, myMember_ALMotion1Stiffness1restStarted_0, myMember_ALMotion1Stiffness1restFinished_0, myMember_ALMotion1Stiffness1wakeUpStarted_0, myMember_ALMotion1Stiffness1wakeUpFinished_0, myMember_RightBumperPressed_0, myMember_LeftBumperPressed_0, myMember_BackBumperPressed_0, myMember_FronTactilTouched_0, myMember_MiddleTactilTouched_0, myMember_RearTactilTouched_0, myMember_HandRightBackTouched_0, myMember_HandLeftBackTouched_0, myMember_FaceDetected_0, myMember_WavingDetection1PersonWaving_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "ALBasicAwareness1HumanTracked":
        return myMember_ALBasicAwareness1HumanTracked_0;
      case "ALBasicAwareness1HumanLost":
        return myMember_ALBasicAwareness1HumanLost_0;
      case "ALBattery1BatteryLow":
        return myMember_ALBattery1BatteryLow_0;
      case "ALChestButton1SimpleClickOccurred":
        return myMember_ALChestButton1SimpleClickOccurred_0;
      case "ALChestButton1DoubleClickOccurred":
        return myMember_ALChestButton1DoubleClickOccurred_0;
      case "ALChestButton1TripleClickOccurred":
        return myMember_ALChestButton1TripleClickOccurred_0;
      case "ALMotion1MoveFailed":
        return myMember_ALMotion1MoveFailed_0;
      case "ALMotion1Stiffness1restStarted":
        return myMember_ALMotion1Stiffness1restStarted_0;
      case "ALMotion1Stiffness1restFinished":
        return myMember_ALMotion1Stiffness1restFinished_0;
      case "ALMotion1Stiffness1wakeUpStarted":
        return myMember_ALMotion1Stiffness1wakeUpStarted_0;
      case "ALMotion1Stiffness1wakeUpFinished":
        return myMember_ALMotion1Stiffness1wakeUpFinished_0;
      case "RightBumperPressed":
        return myMember_RightBumperPressed_0;
      case "LeftBumperPressed":
        return myMember_LeftBumperPressed_0;
      case "BackBumperPressed":
        return myMember_BackBumperPressed_0;
      case "FronTactilTouched":
        return myMember_FronTactilTouched_0;
      case "MiddleTactilTouched":
        return myMember_MiddleTactilTouched_0;
      case "RearTactilTouched":
        return myMember_RearTactilTouched_0;
      case "HandRightBackTouched":
        return myMember_HandRightBackTouched_0;
      case "HandLeftBackTouched":
        return myMember_HandLeftBackTouched_0;
      case "FaceDetected":
        return myMember_FaceDetected_0;
      case "WavingDetection1PersonWaving":
        return myMember_WavingDetection1PersonWaving_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
