package ProjectionalQiChat.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Language extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Language() {
    super(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x6fd223061c49b036L, "Language", "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605878");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_arw_0 = new EnumerationDescriptor.MemberDescriptor("arw", "Arabic", 0x6fd223061c49b037L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605879");
  private final EnumerationDescriptor.MemberDescriptor myMember_czc_0 = new EnumerationDescriptor.MemberDescriptor("czc", "Czech", 0x6fd223061c49b038L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605880");
  private final EnumerationDescriptor.MemberDescriptor myMember_dad_0 = new EnumerationDescriptor.MemberDescriptor("dad", "Danish", 0x6fd223061c49b049L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605897");
  private final EnumerationDescriptor.MemberDescriptor myMember_dun_0 = new EnumerationDescriptor.MemberDescriptor("dun", "Dutch", 0x6fd223061c49b04dL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605901");
  private final EnumerationDescriptor.MemberDescriptor myMember_enu_0 = new EnumerationDescriptor.MemberDescriptor("enu", "English", 0x6fd223061c49b052L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605906");
  private final EnumerationDescriptor.MemberDescriptor myMember_fif_0 = new EnumerationDescriptor.MemberDescriptor("fif", "Finish", 0x6fd223061c49b058L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605912");
  private final EnumerationDescriptor.MemberDescriptor myMember_frf_0 = new EnumerationDescriptor.MemberDescriptor("frf", "French", 0x6fd223061c49b05fL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605919");
  private final EnumerationDescriptor.MemberDescriptor myMember_ged_0 = new EnumerationDescriptor.MemberDescriptor("ged", "German", 0x6fd223061c49b067L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605927");
  private final EnumerationDescriptor.MemberDescriptor myMember_iti_0 = new EnumerationDescriptor.MemberDescriptor("iti", "Italian", 0x6fd223061c49b070L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605936");
  private final EnumerationDescriptor.MemberDescriptor myMember_jpj_0 = new EnumerationDescriptor.MemberDescriptor("jpj", "Japanese", 0x6fd223061c49b07aL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605946");
  private final EnumerationDescriptor.MemberDescriptor myMember_kok_0 = new EnumerationDescriptor.MemberDescriptor("kok", "Korean", 0x6fd223061c49b085L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605957");
  private final EnumerationDescriptor.MemberDescriptor myMember_mnc_0 = new EnumerationDescriptor.MemberDescriptor("mnc", "Chinese", 0x6fd223061c49b091L, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605969");
  private final EnumerationDescriptor.MemberDescriptor myMember_plp_0 = new EnumerationDescriptor.MemberDescriptor("plp", "Polish", 0x6fd223061c49b09eL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605982");
  private final EnumerationDescriptor.MemberDescriptor myMember_ptb_0 = new EnumerationDescriptor.MemberDescriptor("ptb", "Portuguese", 0x6fd223061c49b0acL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470605996");
  private final EnumerationDescriptor.MemberDescriptor myMember_rur_0 = new EnumerationDescriptor.MemberDescriptor("rur", "Russian", 0x6fd223061c49b0bbL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606011");
  private final EnumerationDescriptor.MemberDescriptor myMember_spe_0 = new EnumerationDescriptor.MemberDescriptor("spe", "Spanish", 0x6fd223061c49b0cbL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606027");
  private final EnumerationDescriptor.MemberDescriptor myMember_sws_0 = new EnumerationDescriptor.MemberDescriptor("sws", "Swedish", 0x6fd223061c49b0dcL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606044");
  private final EnumerationDescriptor.MemberDescriptor myMember_trt_0 = new EnumerationDescriptor.MemberDescriptor("trt", "Turkish", 0x6fd223061c49b0eeL, "r:0cc63bc1-1b7d-4deb-8fa2-203bd65036cf(ProjectionalQiChat.structure)/8057541192470606062");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x6fd223061c49b036L, 0x6fd223061c49b037L, 0x6fd223061c49b038L, 0x6fd223061c49b049L, 0x6fd223061c49b04dL, 0x6fd223061c49b052L, 0x6fd223061c49b058L, 0x6fd223061c49b05fL, 0x6fd223061c49b067L, 0x6fd223061c49b070L, 0x6fd223061c49b07aL, 0x6fd223061c49b085L, 0x6fd223061c49b091L, 0x6fd223061c49b09eL, 0x6fd223061c49b0acL, 0x6fd223061c49b0bbL, 0x6fd223061c49b0cbL, 0x6fd223061c49b0dcL, 0x6fd223061c49b0eeL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_arw_0, myMember_czc_0, myMember_dad_0, myMember_dun_0, myMember_enu_0, myMember_fif_0, myMember_frf_0, myMember_ged_0, myMember_iti_0, myMember_jpj_0, myMember_kok_0, myMember_mnc_0, myMember_plp_0, myMember_ptb_0, myMember_rur_0, myMember_spe_0, myMember_sws_0, myMember_trt_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_enu_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "arw":
        return myMember_arw_0;
      case "czc":
        return myMember_czc_0;
      case "dad":
        return myMember_dad_0;
      case "dun":
        return myMember_dun_0;
      case "enu":
        return myMember_enu_0;
      case "fif":
        return myMember_fif_0;
      case "frf":
        return myMember_frf_0;
      case "ged":
        return myMember_ged_0;
      case "iti":
        return myMember_iti_0;
      case "jpj":
        return myMember_jpj_0;
      case "kok":
        return myMember_kok_0;
      case "mnc":
        return myMember_mnc_0;
      case "plp":
        return myMember_plp_0;
      case "ptb":
        return myMember_ptb_0;
      case "rur":
        return myMember_rur_0;
      case "spe":
        return myMember_spe_0;
      case "sws":
        return myMember_sws_0;
      case "trt":
        return myMember_trt_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
