package ProjectionalQiChat.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import ProjectionalQiChat.behavior.EmptyThirdOrderSubrule__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class fix_no_next_emptysubsubsubrule_QuickFix extends QuickFix_Runtime {
  public fix_no_next_emptysubsubsubrule_QuickFix() {
    super(new SNodePointer("r:2e52173d-a6ef-4c74-b7ba-dc1accb9a614(ProjectionalQiChat.typesystem)", "6349347899284287350"));
  }
  public String getDescription(SNode node) {
    return "add new EmptySubsubsubrule as sibling";
  }
  public void execute(SNode node) {
    SNode empty = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x74abec4a81de9592L, "ProjectionalQiChat.structure.EmptyThirdOrderSubrule"));
    EmptyThirdOrderSubrule__BehaviorDescriptor.initializeEmptySubSubSubRule_id7iFV4E1Syz8.invoke(empty);
    SNodeOperations.insertNextSiblingChild(node, empty);
  }
}
