package ProjectionalQiChat.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import ProjectionalQiChat.behavior.HumanConcept__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class fix_OnlyWordChoiceProperty_QuickFix extends QuickFix_Runtime {
  public fix_OnlyWordChoiceProperty_QuickFix() {
    super(new SNodePointer("r:2e52173d-a6ef-4c74-b7ba-dc1accb9a614(ProjectionalQiChat.typesystem)", "678017867208171508"));
  }
  public void execute(SNode node) {
    SPropertyOperations.assign(SNodeOperations.as(node, CONCEPTS.HumanConcept$qf), PROPS.onlyWordChoice$l6_6, (boolean) HumanConcept__BehaviorDescriptor.isInputStoringConfirmed_id2JDDPTEb_xw.invoke(SNodeOperations.as(node, CONCEPTS.HumanConcept$qf)));
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept HumanConcept$qf = MetaAdapterFactory.getConcept(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x6fd223061c49b106L, "ProjectionalQiChat.structure.HumanConcept");
  }

  private static final class PROPS {
    /*package*/ static final SProperty onlyWordChoice$l6_6 = MetaAdapterFactory.getProperty(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x6fd223061c49b106L, 0x4d41c767d8337bb1L, "onlyWordChoice");
  }
}
