package ProjectionalQiChat.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class Condition_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.leftInput$oQQz));
    tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.condition$oQox).getName());
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.rightInput$oRk_));
    if ((SNodeOperations.getNextSibling(ctx.getPrimaryInput()) != null)) {
      tgs.append(" ");
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink leftInput$oQQz = MetaAdapterFactory.getContainmentLink(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x6fd223061c49b339L, 0x4d41c767d8337bf2L, "leftInput");
    /*package*/ static final SContainmentLink rightInput$oRk_ = MetaAdapterFactory.getContainmentLink(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x6fd223061c49b339L, 0x4d41c767d8337bf4L, "rightInput");
  }

  private static final class PROPS {
    /*package*/ static final SProperty condition$oQox = MetaAdapterFactory.getProperty(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x6fd223061c49b339L, 0x4d41c767d8337bf0L, "condition");
  }
}
