package ProjectionalQiChat.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class InputChoice_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.allowRepeat$ljF4)) {
      tgs.append("^repeat");
    }
    tgs.append("[");
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.choices$YXnx)) {
      tgs.appendNode(item);
    }
    tgs.append("] ");
  }

  private static final class PROPS {
    /*package*/ static final SProperty allowRepeat$ljF4 = MetaAdapterFactory.getProperty(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x6fd223061c49b114L, 0x4d41c767d8337bbdL, "allowRepeat");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink choices$YXnx = MetaAdapterFactory.getContainmentLink(0x9f283760f9ca4f5bL, 0x8990d42851344ce7L, 0x6fd223061c49b114L, 0xf8c3893a78b2520L, "choices");
  }
}
